var res = {
    day1_music : "res/Audio/Cannery.wav",
    desk : "res/images/Day1/D1_Neutral_st.png",
    menu : "res/images/menu.png",
    file : "res/images/Day1/D1_File_st.png",
    shred : "res/images/Day1/D1_Shred_st.png",
    outbox : "res/images/Day1/D1_Outbox_st.png",
    arrows : "res/images/Day1/arrow.png",
    office : "res/images/Day1/office.png",
    email : "res/images/email.png",
    
    // Night
    N_BG_png : "res/images/N_PlayBG_test.png",
    N_Player_png : "res/images/N_Player_test.png",
    N_runner_png : "res/images/N_running.png",
    N_runner_plist : "res/images/N_running.plist",
    N_map_png : "res/images/DreamBG.png",
    N_map00_tmx : "res/images/N_map02.tmx",
    N_map01_tmx : "res/images/N_map01.tmx",
    N_checks_png : "res/images/N_checks.png",
    N_checks_plist : "res/images/N_checks.plist",
    
    // Day 2
    D2_run_f1_png: "res/images/Day2/D2_run_f1.png",
    menu : "res/images/menu.png",
    day2bg_png: "res/images/Day2/day2bg.png",
    D2_run_png: "res/images/Day2/D2_run.png",
    D2_run_plist: "res/images/Day2/D2_run.plist",
    D2_jump_png: "res/images/Day2/D2_jump.png",
    D2_jump_plist: "res/images/Day2/D2_jump.plist",
    D2_jump_f1_png: "res/images/Day2/D2_jump_f1.png",
    D2_jump_f2_png: "res/images/Day2/D2_jump_f2.png",
    D2_slide_png: "res/images/Day2/D2_slide.png",
    D2_slide_plist: "res/images/Day2/D2_slide.plist",
    filingcabinet_png: "res/images/Day2/filingcabinet.png",
    desk_png: "res/images/Day2/desk.png",
    trash_png: "res/images/Day2/trash.png",
    coffee_wav: "res/Audio/coffee.wav",
    yum_wav: "res/Audio/yum.wav",
    spill_wav: "res/Audio/spill.wav",
    sabre_mp3: "res/Audio/01-khachaturian-sabre-dance.mp3",
    
    // Day 3
    D3_bg_png: "res/images/Day3/day3bg.png",
    D3_player_png: "res/images/Day3/D3_player_f1.png",
    D3_boss_normal_png: "res/images/Day3/D3_boss_normal.png",
    D3_boss_happy_png: "res/images/Day3/D3_boss_happy.png",
    D3_boss_angry_png: "res/images/Day3/D3_boss_angry.png",

    D3_boss_65_png: "res/images/Day3/65p.png",
    D3_boss_66_png: "res/images/Day3/66p.png",
    D3_boss_68_png: "res/images/Day3/68p.png",
    D3_boss_69_png: "res/images/Day3/69p.png",
    D3_boss_73_png: "res/images/Day3/73p.png",
    D3_boss_76_png: "res/images/Day3/76p.png",
    D3_boss_80_png: "res/images/Day3/80p.png",
    D3_boss_81_png: "res/images/Day3/81p.png",
    D3_boss_83_png: "res/images/Day3/83p.png",
    D3_boss_84_png: "res/images/Day3/84p.png",
    D3_boss_85_png: "res/images/Day3/85p.png",
    D3_player_65_png: "res/images/Day3/65b.png",
    D3_player_66_png: "res/images/Day3/66b.png",
    D3_player_68_png: "res/images/Day3/68b.png",
    D3_player_69_png: "res/images/Day3/69b.png",
    D3_player_73_png: "res/images/Day3/73b.png",
    D3_player_76_png: "res/images/Day3/76b.png",
    D3_player_80_png: "res/images/Day3/80b.png",
    D3_player_81_png: "res/images/Day3/81b.png",
    D3_player_83_png: "res/images/Day3/83b.png",
    D3_player_84_png: "res/images/Day3/84b.png",
    D3_player_85_png: "res/images/Day3/85b.png",
    D3_player_90_png: "res/images/Day3/90p.png",
    
};

var g_resources = [
	res.day1_music,
	res.desk,
	res.menu,
    res.N_BG_png,
    res.N_Player_png,
    res.N_runner_png,
    res.N_runner_plist,
    res.file,
    res.shred,
    res.outbox,
    res.N_map_png,
    res.N_map00_tmx,
    res.N_map01_tmx,
    res.N_checks_png,
    res.N_checks_plist,
    res.arrows,
    res.office,
	res.day2bg_png,
    res.D3_bg_png,
    res.D3_player_png,
    res.D3_boss_normal_png,
    res.D3_boss_happy_png,
    res.D3_boss_angry_png,
    res.D2_run_f1_png,
    res.D2_run_png,
    res.D2_run_plist,
    res.D2_jump_png,
    res.D2_jump_plist,
    res.D2_slide_png,
    res.D2_slide_plist,
    res.filingcabinet_png,
    res.desk_png,
    res.trash_png,
    res.coffee_wav,
    res.yum_wav,
    res.spill_wav,
    res.sabre_mp3,
    res.D3_bg_png,
    res.D3_boss_65_png,
    res.D3_boss_66_png,
    res.D3_boss_68_png,
    res.D3_boss_69_png,
    res.D3_boss_73_png,
    res.D3_boss_76_png,
    res.D3_boss_80_png,
    res.D3_boss_81_png,
    res.D3_boss_83_png,
    res.D3_boss_84_png,

    res.D3_boss_85_png,
    res.D3_player_65_png,
    res.D3_player_66_png,
    res.D3_player_68_png,
    res.D3_player_69_png,
    res.D3_player_73_png,
    res.D3_player_76_png,
    res.D3_player_80_png,
    res.D3_player_81_png,
    res.D3_player_83_png,
    res.D3_player_84_png,
    res.D3_player_85_png,
    res.D3_player_90_png,
];
